#!/usr/bin/env ruby
#
# Copyright (C) 2026 The Waydroid-ATV project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html.
#

libs_32bit  = Dir['prebuilts/lib/arm/*.so'].map { |lib| File.basename(lib, '.so') }
libs_64bit  = Dir['prebuilts/lib64/arm64/*.so'].map { |lib| File.basename(lib, '.so') }
libs_common = libs_32bit & libs_64bit
android_bp  = File.open('Android.bp', 'w')

android_bp.write "// Auto-generated by generate-blueprint.rb, DO NOT MODIFY!\n\n"

[32, 64].each do |arch|
    arch_name = arch == 64 ? 'arm64' : 'arm'
    libdir    = arch == 64 ? 'lib64' : 'lib'

    eval("libs_#{arch}bit - libs_common").each do |lib|
        android_bp.write <<~EOF + "\n"
            cc_prebuilt_library_shared {
                name: "libhoudini-#{lib}",
                stem: "#{lib}",
                check_elf_files: false,
                compile_multilib: "#{arch}",
                relative_install_path: "#{libdir}",
                srcs: ["prebuilts/#{libdir}/#{arch_name}/#{lib}.so"],
                strip: {
                    none: true,
                },
            }
        EOF
    end
end

libs_common.each do |lib|
    android_bp.write <<~EOF + "\n"
        cc_prebuilt_library_shared {
            name: "libhoudini-#{lib}",
            stem: "#{lib}",
            check_elf_files: false,
            compile_multilib: "both",
            arch: {
                x86: {
                    relative_install_path: "arm",
                    srcs: ["prebuilts/lib/arm/#{lib}.so"],
                },
                x86_64: {
                    relative_install_path: "arm64",
                    srcs: ["prebuilts/lib64/arm64/#{lib}.so"],
                },
            },
            strip: {
                none: true,
            },
        }
    EOF
end

android_bp.write <<~EOF
    cc_prebuilt_library_shared {
        name: "libhoudini-cpuinfo",
        stem: "cpuinfo",
        check_elf_files: false,
        compile_multilib: "both",
        arch: {
            x86: {
                relative_install_path: "arm",
                srcs: ["prebuilts/lib/arm/cpuinfo"],
            },
            x86_64: {
                relative_install_path: "arm64",
                srcs: ["prebuilts/lib64/arm64/cpuinfo"],
            },
        },
        strip: {
            none: true,
        },
    }

    cc_prebuilt_library_shared {
        name: "libhoudini",
        check_elf_files: false,
        compile_multilib: "both",
        arch: {
            x86: {
                srcs: ["prebuilts/lib/libhoudini.so"],
                required: [#{(libs_common + libs_32bit).uniq.map { |f| "libhoudini-#{File.basename(f, '.so')}".inspect } .join(', ')}],
            },
            x86_64: {
                srcs: ["prebuilts/lib64/libhoudini.so"],
                required: [#{(libs_common + libs_64bit).uniq.map { |f| "libhoudini-#{File.basename(f, '.so')}".inspect } .join(', ')}],
            },
        },
        strip: {
            none: true,
        },
    }

    cc_prebuilt_binary {
        name: "houdini",
        check_elf_files: false,
        compile_multilib: "both",
        arch: {
            x86: {
                stem: "houdini",
                srcs: ["prebuilts/bin/houdini"],
            },
            x86_64: {
                stem: "houdini64",
                srcs: ["prebuilts/bin/houdini64"],
            },
        },
        init_rc: ["prebuilts/etc/init/houdini.rc"],
        required: ["libhoudini"],
        strip: {
            none: true,
        },
    }
EOF
