#!/usr/bin/env ruby
#
# Copyright (C) 2026 The WayDroid-ATV project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html.
#

android_bp    = File.open('Android.bp', 'w')
libs          = {}
etc_files     = Dir['prebuilts/etc/**/*'].filter_map { |f| File.file?(f) ? f.delete_prefix('prebuilts/etc/') : nil }
libs[:arm]    = Dir['prebuilts/lib/**/*.so'].map { |lib| lib[%r{^prebuilts/lib/(.+)\.so$}, 1] }
libs[:arm64]  = Dir['prebuilts/lib64/**/*.so'].map { |lib| lib[%r{^prebuilts/lib64/(.+)\.so$}, 1] }
libs[:common] = libs[:arm] & libs[:arm64]

android_bp.write "// Auto-generated by generate-blueprint.rb, DO NOT MODIFY!\n\n"

%i[arm arm64].each do |arch|
    (libs[arch] - libs[:common]).each do |lib|
        dirname = File.dirname(lib)
        libname = File.basename(lib)

        android_bp.write <<~EOF + "\n"
            cc_prebuilt_library_shared {
                name: "#{libname.include?('houdini') ? libname : "libhoudini-#{libname}"}",
                stem: "#{libname}",
                check_elf_files: false,
                compile_multilib: "#{arch == :arm ? '32' : '64'}",
                enabled: false,
                arch: {
                    #{arch == :arm ? 'x86' : 'x86_64'}: {
                        enabled: true,
                        relative_install_path: "#{dirname == '.' ? '.' : "#{dirname}/houdini"}",
                        srcs: ["prebuilts/#{arch == :arm ? 'lib' : 'lib64'}/#{lib}.so"],
                    },
                },
                strip: {
                    none: true,
                },
            }
        EOF
    end
end

libs[:common].each do |lib|
    dirname = File.dirname(lib)
    libname = File.basename(lib)

    android_bp.write <<~EOF + "\n"
        cc_prebuilt_library_shared {
            name: "#{libname.include?('houdini') ? libname : "libhoudini-#{libname}"}",
            stem: "#{libname}",
            relative_install_path: "#{dirname == '.' ? '.' : "#{dirname}/houdini"}",
            check_elf_files: false,
            compile_multilib: "both",
            enabled: false,
            arch: {
                x86: {
                    enabled: true,
                    srcs: ["prebuilts/lib/#{lib}.so"],
                },
                x86_64: {
                    enabled: true,
                    srcs: ["prebuilts/lib64/#{lib}.so"],
                },
            },
            strip: {
                none: true,
            },
        }
    EOF
end

etc_files.each do |file|
    filename = File.basename(file)

    android_bp.write <<~EOF + "\n"
        prebuilt_etc {
            name: "#{filename.include?('houdini') ? filename : "libhoudini-#{filename}"}",
            filename: "#{filename}",
            sub_dir: "#{File.dirname(file)}",
            src: "prebuilts/etc/#{file}",
        }
    EOF
end

android_bp.write <<~EOF
    cc_prebuilt_binary {
        name: "houdini",
        check_elf_files: false,
        compile_multilib: "#{libs[:arm].any? ? 'both' : '64'}",
        arch: {
            x86: {
                enabled: #{libs[:arm].any? ? 'true' : 'false'},
                srcs: ["prebuilts/bin/houdini"],
            },
            x86_64: {
                enabled: true,
                srcs: ["prebuilts/bin/houdini64"],
                suffix: "64",
            },
        },
        strip: {
            none: true,
        },
    }
EOF
