# Bundle Houdini as ARM on x86 native bridge
WITH_NATIVE_BRIDGE := true

PRODUCT_PROPERTY_OVERRIDES += \
    ro.enable.native.bridge.exec=1 \
    ro.dalvik.vm.isa.arm64=x86_64 \
    ro.dalvik.vm.native.bridge=libhoudini.so

PRODUCT_PACKAGES += \
    libhoudini \
    libhoudini-aaudio-aidl-cpp \
    libhoudini-aconfig_mediacodec_flags_c_lib \
    libhoudini-aconfig_text_flags_c_lib \
    libhoudini-aconfig_view_accessibility_flags_c_lib \
    libhoudini-android.companion.virtual.virtualdevice_aidl-cpp \
    libhoudini-android.companion.virtualdevice.flags-aconfig-cc \
    libhoudini-android.database.sqlite-aconfig-cc \
    libhoudini-android.hardware.audio.common-V2-ndk \
    libhoudini-android.hardware.audio.common-V3-ndk \
    libhoudini-android.hardware.audio.common-V4-ndk \
    libhoudini-android.hardware.audio.common-V5-ndk \
    libhoudini-android.hardware.audio.core.sounddose-V1-ndk \
    libhoudini-android.hardware.audio.core.sounddose-V2-ndk \
    libhoudini-android.hardware.audio.core.sounddose-V3-ndk \
    libhoudini-android.hardware.audio.core.sounddose-V4-ndk \
    libhoudini-android.hardware.audio.sounddose-V1-ndk \
    libhoudini-android.hardware.audio.sounddose-V2-ndk \
    libhoudini-android.hardware.audio.sounddose-V3-ndk \
    libhoudini-android.hardware.audio.sounddose-V4-ndk \
    libhoudini-android.hardware.camera.common@1.0 \
    libhoudini-android.hardware.camera.device@3.2 \
    libhoudini-android.hardware.cas.native@1.0 \
    libhoudini-android.hardware.cas@1.0 \
    libhoudini-android.hardware.common-V2-cpp \
    libhoudini-android.hardware.common-V2-ndk \
    libhoudini-android.hardware.common.fmq-V1-cpp \
    libhoudini-android.hardware.common.fmq-V1-ndk \
    libhoudini-android.hardware.configstore-utils \
    libhoudini-android.hardware.configstore@1.0 \
    libhoudini-android.hardware.configstore@1.1 \
    libhoudini-android.hardware.contexthub-V5-ndk \
    libhoudini-android.hardware.drm-V1-ndk \
    libhoudini-android.hardware.drm-V2-ndk \
    libhoudini-android.hardware.drm.common-V1-ndk \
    libhoudini-android.hardware.drm@1.0 \
    libhoudini-android.hardware.drm@1.1 \
    libhoudini-android.hardware.drm@1.2 \
    libhoudini-android.hardware.drm@1.3 \
    libhoudini-android.hardware.drm@1.4 \
    libhoudini-android.hardware.graphics.allocator-V1-ndk \
    libhoudini-android.hardware.graphics.allocator-V2-ndk \
    libhoudini-android.hardware.graphics.allocator@2.0 \
    libhoudini-android.hardware.graphics.allocator@3.0 \
    libhoudini-android.hardware.graphics.allocator@4.0 \
    libhoudini-android.hardware.graphics.bufferqueue@1.0 \
    libhoudini-android.hardware.graphics.bufferqueue@2.0 \
    libhoudini-android.hardware.graphics.common-V3-ndk \
    libhoudini-android.hardware.graphics.common-V4-ndk \
    libhoudini-android.hardware.graphics.common-V5-ndk \
    libhoudini-android.hardware.graphics.common-V6-ndk \
    libhoudini-android.hardware.graphics.common-V7-ndk \
    libhoudini-android.hardware.graphics.common@1.0 \
    libhoudini-android.hardware.graphics.common@1.1 \
    libhoudini-android.hardware.graphics.common@1.2 \
    libhoudini-android.hardware.graphics.composer3-V1-ndk \
    libhoudini-android.hardware.graphics.composer3-V2-ndk \
    libhoudini-android.hardware.graphics.composer3-V3-ndk \
    libhoudini-android.hardware.graphics.composer3-V4-ndk \
    libhoudini-android.hardware.graphics.composer3-V5-ndk \
    libhoudini-android.hardware.graphics.mapper@2.0-impl-2.1 \
    libhoudini-android.hardware.graphics.mapper@2.0-impl \
    libhoudini-android.hardware.graphics.mapper@2.0 \
    libhoudini-android.hardware.graphics.mapper@2.1 \
    libhoudini-android.hardware.graphics.mapper@3.0 \
    libhoudini-android.hardware.graphics.mapper@4.0 \
    libhoudini-android.hardware.media.bufferpool2-V1-ndk \
    libhoudini-android.hardware.media.bufferpool2-V2-ndk \
    libhoudini-android.hardware.media.bufferpool@2.0 \
    libhoudini-android.hardware.media.c2-V1-ndk \
    libhoudini-android.hardware.media.c2-V2-ndk \
    libhoudini-android.hardware.media.c2@1.0 \
    libhoudini-android.hardware.media.c2@1.1 \
    libhoudini-android.hardware.media.c2@1.2 \
    libhoudini-android.hardware.media.omx@1.0 \
    libhoudini-android.hardware.media@1.0 \
    libhoudini-android.hardware.memtrack-V1-ndk \
    libhoudini-android.hardware.memtrack@1.0 \
    libhoudini-android.hardware.power-V3-cpp \
    libhoudini-android.hardware.power-V4-cpp \
    libhoudini-android.hardware.power-V4-ndk \
    libhoudini-android.hardware.power-V5-ndk \
    libhoudini-android.hardware.power-V6-ndk \
    libhoudini-android.hardware.power-V7-ndk \
    libhoudini-android.hardware.power@1.0 \
    libhoudini-android.hardware.power@1.1 \
    libhoudini-android.hardware.power@1.2 \
    libhoudini-android.hardware.power@1.3 \
    libhoudini-android.hardware.renderscript@1.0 \
    libhoudini-android.hidl.allocator@1.0 \
    libhoudini-android.hidl.memory.token@1.0 \
    libhoudini-android.hidl.memory@1.0-impl \
    libhoudini-android.hidl.memory@1.0 \
    libhoudini-android.hidl.safe_union@1.0 \
    libhoudini-android.hidl.token@1.0-utils \
    libhoudini-android.hidl.token@1.0 \
    libhoudini-android.media.audio.common.types-V1-cpp \
    libhoudini-android.media.audio.common.types-V2-cpp \
    libhoudini-android.media.audio.common.types-V2-ndk \
    libhoudini-android.media.audio.common.types-V3-cpp \
    libhoudini-android.media.audio.common.types-V3-ndk \
    libhoudini-android.media.audio.common.types-V4-cpp \
    libhoudini-android.media.audio.common.types-V4-ndk \
    libhoudini-android.media.audio.common.types-V5-cpp \
    libhoudini-android.media.audio.common.types-V5-ndk \
    libhoudini-android.media.audiopolicy-aconfig-cc \
    libhoudini-android.os.flags-aconfig-cc-host \
    libhoudini-android.os.flags-aconfig-cc \
    libhoudini-android.system.suspend-V1-ndk \
    libhoudini-android.system.virtualizationcommon-ndk \
    libhoudini-android.system.virtualizationservice-ndk \
    libhoudini-audio-permission-aidl-cpp \
    libhoudini-audioclient-types-aidl-cpp \
    libhoudini-audioflinger-aidl-cpp \
    libhoudini-audiopermissioncontroller \
    libhoudini-audiopolicy-aidl-cpp \
    libhoudini-audiopolicy-types-aidl-cpp \
    libhoudini-av-types-aidl-cpp \
    libhoudini-camera_platform_flags_c_lib \
    libhoudini-capture_state_listener-aidl-cpp \
    libhoudini-com.android.media.aaudio-aconfig-cc \
    libhoudini-com.android.media.audio-aconfig-cc \
    libhoudini-com.android.media.audioclient-aconfig-cc \
    libhoudini-com.android.media.audioserver-aconfig-cc \
    libhoudini-com.android.window.flags.window-aconfig_flags_c_lib \
    libhoudini-contexthub_data_flow \
    libhoudini-dynamic_instrumentation_manager_aidl-cpp \
    libhoudini-effect-aidl-cpp \
    libhoudini-framework-permission-aidl-cpp \
    libhoudini-gralloc.minigbm \
    libhoudini-graphicbuffersource-aidl-ndk \
    libhoudini-heapprofd_client_api \
    libhoudini-ld-android \
    libhoudini-lib-camera-compatibility-info-api \
    libhoudini-lib-platform-compat-native-api \
    libhoudini-libEGL \
    libhoudini-libEGL_angle \
    libhoudini-libETC1 \
    libhoudini-libGLESv1_CM \
    libhoudini-libGLESv1_CM_angle \
    libhoudini-libGLESv2 \
    libhoudini-libGLESv2_angle \
    libhoudini-libGLESv3 \
    libhoudini-libOpenMAXAL \
    libhoudini-libOpenSLES \
    libhoudini-libPlatformProperties \
    libhoudini-libRS \
    libhoudini-libRSCacheDir \
    libhoudini-libRSCpuRef \
    libhoudini-libRSDriver \
    libhoudini-libRS_internal \
    libhoudini-libRScpp \
    libhoudini-libSurfaceFlingerProp \
    libhoudini-libaaudio \
    libhoudini-libaaudio_internal \
    libhoudini-libaaudio_internal_builder \
    libhoudini-libaaudio_internal_core \
    libhoudini-libaaudio_internal_fifo \
    libhoudini-libaaudio_internal_legacy \
    libhoudini-libaaudio_internal_mmap \
    libhoudini-libaaudio_internal_utils \
    libhoudini-libaconfig_storage_read_api_cc \
    libhoudini-libactivitymanager_aidl \
    libhoudini-libamidi \
    libhoudini-libandroid \
    libhoudini-libandroid_net \
    libhoudini-libandroid_runtime \
    libhoudini-libandroid_runtime_lazy \
    libhoudini-libandroidfw \
    libhoudini-libandroidicu \
    libhoudini-libapexsupport \
    libhoudini-libappfuse \
    libhoudini-libart-compiler \
    libhoudini-libart-disassembler \
    libhoudini-libart-simulator-container \
    libhoudini-libart \
    libhoudini-libartbase \
    libhoudini-libartbased \
    libhoudini-libartpalette-system \
    libhoudini-libartpalette \
    libhoudini-libaudio_aidl_conversion_common_cpp \
    libhoudini-libaudio_aidl_conversion_common_ndk \
    libhoudini-libaudioclient \
    libhoudini-libaudioclient_aidl_conversion \
    libhoudini-libaudioflinger \
    libhoudini-libaudioflinger_datapath \
    libhoudini-libaudioflinger_fastpath \
    libhoudini-libaudioflinger_timing \
    libhoudini-libaudioflinger_utils \
    libhoudini-libaudiofoundation \
    libhoudini-libaudiohal \
    libhoudini-libaudiomanager \
    libhoudini-libaudiopermission \
    libhoudini-libaudiopolicy \
    libhoudini-libaudioprocessing \
    libhoudini-libaudiospdif \
    libhoudini-libaudioutils \
    libhoudini-libbacktrace \
    libhoudini-libbase \
    libhoudini-libbattery \
    libhoudini-libbcinfo \
    libhoudini-libbinder \
    libhoudini-libbinder_ndk \
    libhoudini-libbinderdebug \
    libhoudini-libblas \
    libhoudini-libbpf_bcc \
    libhoudini-libbpf_minimal \
    libhoudini-libbufferhub \
    libhoudini-libbufferhubqueue \
    libhoudini-libc++ \
    libhoudini-libc \
    libhoudini-libcamera2ndk \
    libhoudini-libcamera_client \
    libhoudini-libcamera_metadata \
    libhoudini-libcameracompatbilityinfo \
    libhoudini-libcap \
    libhoudini-libcgrouprc \
    libhoudini-libclang_rt.asan-aarch64-android \
    libhoudini-libclang_rt.hwasan-aarch64-android \
    libhoudini-libclang_rt.ubsan_standalone-aarch64-android \
    libhoudini-libcodec2 \
    libhoudini-libcodec2_aidl \
    libhoudini-libcodec2_aidl_client \
    libhoudini-libcodec2_client \
    libhoudini-libcodec2_hal_common \
    libhoudini-libcodec2_hidl@1.0 \
    libhoudini-libcodec2_hidl@1.1 \
    libhoudini-libcodec2_hidl@1.2 \
    libhoudini-libcodec2_hidl_client@1.0 \
    libhoudini-libcodec2_hidl_client@1.1 \
    libhoudini-libcodec2_hidl_client@1.2 \
    libhoudini-libcodec2_soft_common \
    libhoudini-libcodec2_vndk \
    libhoudini-libcompiler_rt \
    libhoudini-libcore_jni_flags_c \
    libhoudini-libcrypto \
    libhoudini-libcutils \
    libhoudini-libdataloader \
    libhoudini-libdatasource \
    libhoudini-libdebuggerd_client \
    libhoudini-libdebugstore_cxx \
    libhoudini-libdexfile \
    libhoudini-libdl \
    libhoudini-libdl_android \
    libhoudini-libdmabufheap \
    libhoudini-libdng_sdk \
    libhoudini-libdrm \
    libhoudini-libegl_flags \
    libhoudini-libexpat \
    libhoudini-libfmq \
    libhoudini-libft2 \
    libhoudini-libgralloctypes \
    libhoudini-libgraphicsenv \
    libhoudini-libgui \
    libhoudini-libhardware \
    libhoudini-libhardware_legacy \
    libhoudini-libharfbuzz_ng \
    libhoudini-libharfbuzz_subset \
    libhoudini-libheif \
    libhoudini-libhidl-gen-utils \
    libhoudini-libhidlallocatorutils \
    libhoudini-libhidlbase \
    libhoudini-libhidlmemory \
    libhoudini-libhwui \
    libhoudini-libicu \
    libhoudini-libicu_jni \
    libhoudini-libicui18n \
    libhoudini-libicuuc \
    libhoudini-libimage_io \
    libhoudini-libimg_utils \
    libhoudini-libincfs \
    libhoudini-libinput \
    libhoudini-libion \
    libhoudini-libjnigraphics \
    libhoudini-libjpeg \
    libhoudini-libjpegdecoder \
    libhoudini-libjpegencoder \
    libhoudini-libjxl \
    libhoudini-liblog \
    libhoudini-liblog_rust.dylib \
    libhoudini-liblz4 \
    libhoudini-liblzma \
    libhoudini-libm \
    libhoudini-libmedia \
    libhoudini-libmedia_codeclist \
    libhoudini-libmedia_codeclist_capabilities \
    libhoudini-libmedia_helper \
    libhoudini-libmedia_jni_utils \
    libhoudini-libmedia_omx \
    libhoudini-libmedia_omx_client \
    libhoudini-libmedia_quality_include \
    libhoudini-libmediadrm \
    libhoudini-libmediadrmmetrics_lite \
    libhoudini-libmediaformatshaper \
    libhoudini-libmedialogservice \
    libhoudini-libmediametrics \
    libhoudini-libmediandk \
    libhoudini-libmediandk_utils \
    libhoudini-libmediatranscoder \
    libhoudini-libmediatranscoding \
    libhoudini-libmediautils \
    libhoudini-libmeminfo \
    libhoudini-libmemtrack \
    libhoudini-libmemunreachable \
    libhoudini-libminigbm_gralloc \
    libhoudini-libminijail \
    libhoudini-libminikin \
    libhoudini-libnativebridge \
    libhoudini-libnativebridge_lazy \
    libhoudini-libnativedisplay \
    libhoudini-libnativehelper \
    libhoudini-libnativeloader \
    libhoudini-libnativeloader_lazy \
    libhoudini-libnativewindow \
    libhoudini-libnbaio \
    libhoudini-libnblog \
    libhoudini-libnetd_client \
    libhoudini-libnetdutils \
    libhoudini-libnetworkstats \
    libhoudini-libneuralnetworks \
    libhoudini-libneuralnetworks_packageinfo \
    libhoudini-libonce_cell.dylib \
    libhoudini-libopus \
    libhoudini-libpackagelistparser \
    libhoudini-libpcre2 \
    libhoudini-libpdfium \
    libhoudini-libpdx_default_transport \
    libhoudini-libperfetto_c \
    libhoudini-libperfetto_framework_jni \
    libhoudini-libpermission \
    libhoudini-libpiex \
    libhoudini-libpng \
    libhoudini-libpowermanager \
    libhoudini-libprocessgroup \
    libhoudini-libprocinfo \
    libhoudini-libprofile \
    libhoudini-libprotobuf-cpp-lite-6.33.1 \
    libhoudini-libprotobuf-cpp-lite \
    libhoudini-libprotolog \
    libhoudini-libselinux \
    libhoudini-libsensor \
    libhoudini-libsfplugin_ccodec \
    libhoudini-libsfplugin_ccodec_utils \
    libhoudini-libshmemcompat \
    libhoudini-libshmemutil \
    libhoudini-libsigchain \
    libhoudini-libsonic \
    libhoudini-libsounddose \
    libhoudini-libspeexresampler \
    libhoudini-libsqlite \
    libhoudini-libssl \
    libhoudini-libstagefright \
    libhoudini-libstagefright_aidl_bufferpool2 \
    libhoudini-libstagefright_amrnb_common \
    libhoudini-libstagefright_bufferpool@2.0.1 \
    libhoudini-libstagefright_bufferqueue_helper \
    libhoudini-libstagefright_bufferqueue_helper_novndk \
    libhoudini-libstagefright_codecbase \
    libhoudini-libstagefright_enc_common \
    libhoudini-libstagefright_flacdec \
    libhoudini-libstagefright_foundation \
    libhoudini-libstagefright_framecapture_utils \
    libhoudini-libstagefright_graphicbuffersource_aidl \
    libhoudini-libstagefright_http_support \
    libhoudini-libstagefright_omx \
    libhoudini-libstagefright_omx_utils \
    libhoudini-libstagefright_persistentsurface \
    libhoudini-libstagefright_surface_utils \
    libhoudini-libstagefright_xmlparser \
    libhoudini-libstatspull \
    libhoudini-libstatssocket \
    libhoudini-libstd.dylib \
    libhoudini-libstdc++ \
    libhoudini-libsync \
    libhoudini-libtimeinstate \
    libhoudini-libtinyxml2 \
    libhoudini-libtombstoned_client \
    libhoudini-libtracing_perfetto \
    libhoudini-libui \
    libhoudini-libultrahdr \
    libhoudini-libunwindstack \
    libhoudini-libusbhost \
    libhoudini-libutils \
    libhoudini-libutilscallstack \
    libhoudini-libvibrator \
    libhoudini-libvintf \
    libhoudini-libvndksupport \
    libhoudini-libvpx \
    libhoudini-libvulkan \
    libhoudini-libwebviewchromium_plat_support \
    libhoudini-libwilhelm \
    libhoudini-libxml2 \
    libhoudini-libz \
    libhoudini-libziparchive \
    libhoudini-media_quality_aidl_interface-cpp \
    libhoudini-mediametricsservice-aidl-cpp \
    libhoudini-packagemanager_aidl-cpp \
    libhoudini-process_info_service_aidl-cpp \
    libhoudini-pw_allocator \
    libhoudini-server_configurable_flags \
    libhoudini-shared-file-region-aidl-cpp \
    libhoudini-spatializer-aidl-cpp \
    libhoudini-volumegroupcallback-aidl-cpp \
    libhoudini \
    libhoudini-libtcb \
    houdini \
    houdini.rc \
    libhoudini-cpuinfo.arm64.txt
